spring:
  application:
    name: springcloud2-producer
  datasource:
    username: root
    password: Effective
    url: jdbc:mysql://127.0.0.1:3306/rain?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    # database-platform: cn.luutqf.springboot.dialect.JsonbPostgresDialect
    hibernate:
      ddl-auto: update  # none: 关闭hibernate的自动创建表结构的机制
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql

  aop:
    auto: true
    proxy-target-class: true


eureka:
  instance:
    prefer-ip-address: false
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://192.168.0.57:9101/eureka/

info:
  app:
     name: springcloud2-producer

server:
  port: 8092